@echo off
echo Uninstalling Tailwind v4...
call npm uninstall tailwindcss @tailwindcss/postcss
echo Installing Tailwind v3...
call npm install -D tailwindcss@3.4.17 postcss autoprefixer
echo Running Build...
call npm run build
